### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by teloe** [source-foundry/Hack#595]
i'm attempting to build ttf fonts using alternative glyphs from the [alt hack repo](https://github.com/source-foundry/alt-hack). i downloaded/unpacked from the dev branch.

macos big sur 11.6
fonttools v4.33.3
fontmake 3.3.0
ttfauthohint 1.8.4

i've run:
```
$ pip3 install pipenv
$ make compile-local-dep
$ make
```

i'm getting this output:
```
./build-pipenv.sh
/Library/Frameworks/Python.framework/Versions/3.10/bin/pipenv
Installing dependencies from Pipfile.lock (79fc86)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
Looking in indexes: https://pypi.python.org/simple
Ignoring lxml: markers 'extra == "lxml"' don't match your environment
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
1.7.5
=================================
  PYTHON BUILD ENVIRONMENT
=================================
 
Python interpreter version:
Python 3.7.13
 
fontmake==1.7.5
  - booleanOperations [required: >=0.8.0, installed: 0.8.0]
    - fonttools [required: >=3.1.2, installed: 3.30.0]
    - pyclipper [required: >=1.0.5, installed: 1.1.0.post1]
    - ufoLib [required: >=2.0.0, installed: 2.3.2]
      - fonttools [required: >=3.1.2,<4, installed: 3.30.0]
  - cu2qu [required: >=1.5.0, installed: 1.6.4]
    - fonttools [required: >=3.18.0, installed: 3.30.0]
    - ufoLib [required: >=2.1.1, installed: 2.3.2]
      - fonttools [required: >=3.1.2,<4, installed: 3.30.0]
  - defcon [required: >=0.5.3, installed: 0.5.3]
    - fonttools [required: >=3.1.2, installed: 3.30.0]
    - ufoLib [required: >=2.3.1, installed: 2.3.2]
      - fonttools [required: >=3.1.2,<4, installed: 3.30.0]
  - fonttools [required: >=3.30.0, installed: 3.30.0]
  - glyphsLib [required: >=3.1.2, installed: 3.1.2]
    - defcon [required: >=0.3.0, installed: 0.5.3]
      - fonttools [required: >=3.1.2, installed: 3.30.0]
      - ufoLib [required: >=2.3.1, installed: 2.3.2]
        - fonttools [required: >=3.1.2,<4, installed: 3.30.0]
    - fonttools [required: >=3.24.0, installed: 3.30.0]
  - MutatorMath [required: >=2.1.1, installed: 2.1.1]
    - defcon [required: >=0.3.5, installed: 0.5.3]
      - fonttools [required: >=3.1.2, installed: 3.30.0]
      - ufoLib [required: >=2.3.1, installed: 2.3.2]
        - fonttools [required: >=3.1.2,<4, installed: 3.30.0]
    - fontMath [required: >=0.4.4, installed: 0.4.7]
      - fonttools [required: >=3.3.0, installed: 3.30.0]
      - ufoLib [required: >=2.0.0, installed: 2.3.2]
        - fonttools [required: >=3.1.2,<4, installed: 3.30.0]
    - ufoLib [required: >=2.0.0, installed: 2.3.2]
      - fonttools [required: >=3.1.2,<4, installed: 3.30.0]
  - ufo2ft [required: >=2.4.0, installed: 2.4.0]
    - booleanOperations [required: >=0.8.0, installed: 0.8.0]
      - fonttools [required: >=3.1.2, installed: 3.30.0]
      - pyclipper [required: >=1.0.5, installed: 1.1.0.post1]
      - ufoLib [required: >=2.0.0, installed: 2.3.2]
        - fonttools [required: >=3.1.2,<4, installed: 3.30.0]
    - compreffor [required: >=0.4.5, installed: 0.4.6.post1]
      - fonttools [required: >=3.1, installed: 3.30.0]
    - cu2qu [required: >=1.5.0, installed: 1.6.4]
      - fonttools [required: >=3.18.0, installed: 3.30.0]
      - ufoLib [required: >=2.1.1, installed: 2.3.2]
        - fonttools [required: >=3.1.2,<4, installed: 3.30.0]
    - defcon [required: >=0.4.0, installed: 0.5.3]
      - fonttools [required: >=3.1.2, installed: 3.30.0]
      - ufoLib [required: >=2.3.1, installed: 2.3.2]
        - fonttools [required: >=3.1.2,<4, installed: 3.30.0]
    - fonttools [required: >=3.28.0, installed: 3.30.0]
    - ufoLib [required: >=2.1.0, installed: 2.3.2]
      - fonttools [required: >=3.1.2,<4, installed: 3.30.0]
  - ufoLib [required: >=2.3.1, installed: 2.3.2]
    - fonttools [required: >=3.1.2,<4, installed: 3.30.0]
 
=================================
 
=================================
 
./build-ttf.sh
fatal: not a git repository (or any of the parent directories): .git
Starting build...
 
INFO:fontmake.font_project:Building TTF for Hack-Regular
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Hack-Regular
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on Hack-Regular
INFO:ufo2ft.filters:Running CubicToQuadraticFilter on Hack-Regular
INFO:ufo2ft.filters.cubicToQuadratic:New spline lengths: 1: 4655, 2: 4082, 3: 541, 4: 89, 5: 17
INFO:ufo2ft:Building OpenType tables
Traceback (most recent call last):
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/bin/fontmake", line 8, in <module>
    sys.exit(main())
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/fontmake/__main__.py", line 274, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/fontmake/font_project.py", line 688, in run_from_ufos
    self.build_ttfs(ufos, **kwargs)
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/fontmake/font_project.py", line 245, in build_ttfs
    self.save_otfs(ufos, ttf=True, **kwargs)
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/fontmake/font_project.py", line 408, in save_otfs
    for font, ufo in zip(fonts, ufos):
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/fontmake/font_project.py", line 289, in _iter_compile
    yield compile_func(ufo, **options)
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/ufo2ft/__init__.py", line 155, in compileTTF
    postProcessor = PostProcessor(otf, ufo, glyphSet=glyphSet)
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/ufo2ft/postProcessor.py", line 29, in __init__
    otf.save(stream)
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 173, in save
    writer_reordersTables = self._save(tmp)
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 212, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 633, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 651, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/fontTools/ttLib/tables/_h_e_a_d.py", line 68, in compile
    self.modified = timestampNow()
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/fontTools/misc/timeTools.py", line 54, in timestampNow
    return int(source_date_epoch) - epoch_diff
ValueError: invalid literal for int() with base 10: ''
Unable to build the Hack-Regular variant set.  Build canceled.
make: *** [ttf] Error 1
```

i'm also attempting to run with system PATH installed build dependencies:
```
make ttf-system
```

and getting this output:
```
./build-ttf.sh --system
fatal: not a git repository (or any of the parent directories): .git
=================================
  BUILD ENVIRONMENT
=================================
/opt/homebrew/bin/ttfautohint
ttfautohint 1.8.4
Copyright (C) 2011-2021 Werner Lemberg <wl@gnu.org>.
License: FreeType License (FTL) or GNU GPLv2.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
/opt/homebrew/bin/fontmake
3.3.0
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3
Python 3.10.5
=================================
 
=================================
 
Starting build...
 
INFO:fontmake.font_project:Building TTF for Hack-Regular
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters.base:Running DecomposeComponentsFilter on Hack-Regular
INFO:ufo2ft.filters.base:Running RemoveOverlapsFilter on Hack-Regular
INFO:ufo2ft.filters.base:Running CubicToQuadraticFilter on Hack-Regular
INFO:ufo2ft.filters.cubicToQuadratic:New spline lengths: 1: 4655, 2: 4082, 3: 541, 4: 89, 5: 17
INFO:ufo2ft:Building OpenType tables
fontmake: Error: In 'source/Hack-Regular.ufo': Compiling UFO failed: invalid literal for int() with base 10: ''
Unable to build the Hack-Regular variant set.  Build canceled.
make: *** [ttf-system] Error 1
```

any help would be much appreciated!

**Comment by allenrsty** [comment]
I'm also getting this error. Any suggestions on how to fix?

```
  File "/Users/tomeloe/.local/share/virtualenvs/Hack-dev-X4lraJb1/lib/python3.7/site-packages/fontTools/misc/timeTools.py", line 54, in timestampNow
    return int(source_date_epoch) - epoch_diff
ValueError: invalid literal for int() with base 10: ''
```
